### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jungwuk-ryu** [KISH-students/KISH_app#1]
- KISH magazine
- [ ] 기사 등록
- [ ] 기사 조회
- [ ] 기사 언어별로 보기
- [ ] 년도별 조회

- 도서관 관련
- [ ] 로그인
- [ ] 회원가입
- [ ] 비밀번호 찾기
- [ ] 대출 현황 보기 ( 내 정보 )
- [ ] 도서 검색
- [ ] 추천 도서 조회

- 게시물
- [ ] 익명게시판
- [ ] 분실물
- [ ] ~~물건 나눔~~

- 가정통신문 ( 학교 홈페이지 게시물 )
- [ ] 게시물 조회
- [ ] 게시물 검색
- [ ] 게시물 카테고리
- [ ] 게시물 댓글 등록
- [ ] 새 게시물 알림

- 일반
- [ ] 학사 일정 ( 학교 행사 )
- [ ] 급식 알림
- [ ] 급식 알림 ( notification )
- [ ] 시험 D-Day
- [ ] 시험 D-Day 상태바 알림

**Comment by jungwuk-ryu** [comment]
Move to https://github.com/KISH-students/KISH_app/pull/2
