### ISSUE TITLE
new TODO

### ISSUE THREAD

**Issue by jungwuk-ryu** [KISH-students/KISH_app#3]
아래 TODO는 #2  이후에 기본적으로 구현되어야 할 기능들을 나열합니다.

- 도서관 관련
- [x] 로그인
- [x] 로그아웃
- [x] 회원가입
- [ ] 비밀번호 찾기
- [x] 내 정보
- [ ] 대출 현황 보기
- [ ] 도서 검색
- [ ] 추천 도서 조회
- 가정통신문 ( 학교 홈페이지 게시물 )
- [x] 게시물 조회
- [x] 게시물 검색
- [x] 게시물 카테고리
- [x] 새 게시물 알림
- [x] 게시물 더 보기
- [x] 게시물 첨부파일 처리
- 일반
- [] ~학사 일정 ( 학교 행사 )~~
- [x] 급식 알림 ( notification )
- [x] 시험 D-Day 상태바 알림
